### PR TITLE
Bump `voprf` to v0.5.0-pre.2

### PR DESCRIPTION
**Pull request by daxpedda**
Depends on https://github.com/facebook/voprf/pull/90 and https://github.com/facebook/voprf/pull/102.
The upgrade to Rust 1.60 also necessitated some Clippy fixes.

### CODE REVIEW

**Comment by daxpedda** [comment]
Broken by https://github.com/kkawakam/rustyline/issues/671.
Happy to increase it to 1.62 too, but I'm assuming that `rustyline` will actually address this.

**Comment by kevinlewi** [comment]
Thanks for checking! Yes, 1.62 should be fine. Let's increase it to that.

**Comment by daxpedda** [comment]
Will adjust after the VOPRF PR gets merged and released.

**Comment by daxpedda** [comment]
`rustyline` already fixed it. I will update the minimum version on my next push.

**Comment by daxpedda** [comment]
Done, waiting for a `voprf` release now.

**Comment by daxpedda** [comment]
Now also builds on top of https://github.com/facebook/voprf/pull/102.

**Comment by daxpedda** [comment]
This is ready now.

**Review by kevinlewi — APPROVED** [review]
Thanks again!

**Pull request merged**
