### PR TITLE
Test P-384

### PR DESCRIPTION
**Pull request by daxpedda**
This just tests P-384 support and builds on top of https://github.com/novifinancial/voprf/pull/84, which builds on top of https://github.com/RustCrypto/elliptic-curves/pull/600.
We still have to wait for new versions to be released.

~~This also builds on top of https://github.com/novifinancial/opaque-ke/pull/288, which builds on top of https://github.com/novifinancial/opaque-ke/pull/289.~~
Builds on top of https://github.com/facebook/opaque-ke/pull/307.

### CODE REVIEW

**Comment by daxpedda** [comment]
Rebased after #289 and #288.

**Comment by daxpedda** [comment]
Rebased after #298.

**Comment by daxpedda** [comment]
Rebased after #307, this is ready now!

**Review by kevinlewi — APPROVED** [review]
Thanks!!

**Pull request merged**
