### PR TITLE
Test P-521

### PR DESCRIPTION
**Pull request by daxpedda**
This adds testing of P-521 through the [`p521`](https://crates.io/crates/p521) crate.

Still requires:
- [x] https://github.com/RustCrypto/elliptic-curves/pull/964
- [x] https://github.com/RustCrypto/elliptic-curves/issues/965

See #290 for a previously similar addition.
See https://github.com/facebook/voprf/pull/127 for the same PR in `voprf`, which isn't required to merge this.

### CODE REVIEW

**Comment by daxpedda** [comment]
CI fails because of https://github.com/RustCrypto/elliptic-curves/issues/965, which we are going to wait for anyway.

**Comment by daxpedda** [comment]
This is ready to merge now.

**Comment by kevinlewi** [comment]
It seems like the maintenance for full_test.rs is getting more and more cumbersome now... any thoughts for how we can make this simpler?

And maybe for now, can you also add (in a comment above each new set of constants in full_test.rs) instructions for the cargo command to re-generate those constants?

**Comment by daxpedda** [comment]
Last two commits should address both concerns.
WDYT?

**Review by kevinlewi — APPROVED** [review]
Oh wow, this is really awesome -- thank you for that refactor! Looks good to me

**Pull request merged**
